package com.corebank.coreb.service;

import com.corebank.coreb.dto.RepaymentReportDTO;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;
import java.util.List;
import org.springframework.stereotype.Service;
import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public class PdfReportService {
	// Page event to add footer with page numbers
	static class FooterPageEvent extends PdfPageEventHelper {
	    Font footerFont = new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL, BaseColor.GRAY);

	    @Override
	    public void onEndPage(PdfWriter writer, Document document) {

	        PdfPTable footer = new PdfPTable(1);
	        footer.setTotalWidth(document.getPageSize().getWidth() - document.leftMargin() - document.rightMargin());
	        footer.getDefaultCell().setBorder(Rectangle.NO_BORDER);
	        footer.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);

	        Phrase phrase = new Phrase("Page " + writer.getPageNumber(), footerFont);
	        footer.addCell(phrase);

	        footer.writeSelectedRows(
	                0,
	                -1,
	                document.leftMargin(),
	                document.bottomMargin() - 5,
	                writer.getDirectContent()
	        );
	    }
	}

    public byte[] generatePdfReportModernBanking(List<RepaymentReportDTO> reportData, String generatedBy) {
        DateTimeFormatter df = DateTimeFormatter.ofPattern("dd-MMM-yyyy");
        // Colors
        BaseColor NAVY = new BaseColor(10, 48, 97);         // deep navy
        BaseColor GOLD = new BaseColor(199, 153, 39);       // gold accent
        BaseColor HEADER_BG = NAVY;
        BaseColor HEADER_TEXT = BaseColor.WHITE;
        BaseColor ROW_ALT = new BaseColor(245, 247, 250);   // light gray for alt rows

        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document document = new Document(PageSize.A4, 36, 36, 90, 60); // left, right, top, bottom margins
            PdfWriter writer = PdfWriter.getInstance(document, out);
            writer.setPageEvent(new FooterPageEvent());
            document.open();

            // ---------- Header (Navy bar with logo + title + date) ----------
            PdfPTable headerTable = new PdfPTable(new float[]{1, 3});
            headerTable.setWidthPercentage(100);
            headerTable.getDefaultCell().setBorder(Rectangle.NO_BORDER);

            // Logo cell (placeholder)
            PdfPCell logoCell = new PdfPCell();
            logoCell.setBackgroundColor(HEADER_BG);
            logoCell.setBorder(Rectangle.NO_BORDER);
            logoCell.setPadding(10f);
            Paragraph logoP = new Paragraph();
            logoP.setAlignment(Element.ALIGN_LEFT);
            Font logoFont = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD, HEADER_TEXT);
            logoP.add(new Chunk("COREBANK", logoFont));
            logoP.add(Chunk.NEWLINE);
            Font slogan = new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL, HEADER_TEXT);
            logoP.add(new Chunk("Trusted Finance Solutions", slogan));
            logoCell.addElement(logoP);

            // Title / meta cell
            PdfPCell titleCell = new PdfPCell();
            titleCell.setBackgroundColor(HEADER_BG);
            titleCell.setBorder(Rectangle.NO_BORDER);
            titleCell.setPadding(12f);

            Font titleFont = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD, HEADER_TEXT);
            Font metaFont = new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL, HEADER_TEXT);

            Paragraph titleP = new Paragraph();
            titleP.setAlignment(Element.ALIGN_RIGHT);
            titleP.add(new Chunk("Loan Repayment Report\n", titleFont));
            titleP.add(new Chunk("Generated on: " + java.time.LocalDate.now().format(df) + "\n", metaFont));
            if (generatedBy != null && !generatedBy.isEmpty()) {
                titleP.add(new Chunk("Generated by: " + generatedBy, metaFont));
            }
            titleCell.addElement(titleP);

            headerTable.addCell(logoCell);
            headerTable.addCell(titleCell);
            document.add(headerTable);

            document.add(Chunk.NEWLINE);

            // ---------- Loan summary box (light background) ----------
            PdfPTable summaryTable = new PdfPTable(4);
            summaryTable.setWidthPercentage(100);
            summaryTable.setSpacingBefore(6f);
            summaryTable.setSpacingAfter(10f);
            summaryTable.setWidths(new float[]{1, 2, 1, 2});
            summaryTable.getDefaultCell().setBorder(Rectangle.NO_BORDER);

            Font labelFont = new Font(Font.FontFamily.HELVETICA, 9, Font.BOLD, BaseColor.DARK_GRAY);
            Font valueFont = new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL, BaseColor.BLACK);

            // Extract a few summary values from the first record if available
            String loanId = reportData != null && !reportData.isEmpty() && reportData.get(0).getLoanId() != null
                    ? String.valueOf(reportData.get(0).getLoanId())
                    : "-";
            String rateOfInterest = reportData != null && !reportData.isEmpty() && reportData.get(0).getRateofinterest() != null
                    ? reportData.get(0).getRateofinterest().toPlainString() + "%"
                    : "-";

            BigDecimal principalNotAvailable = null; // user said fields limited; keep placeholder
            String tenurePlaceholder = "-";
            String loanTypePlaceholder = "-";
            String customerPlaceholder = "-";

            // Row 1
            PdfPCell c1 = new PdfPCell(new Phrase("Loan ID", labelFont));
            c1.setBorder(Rectangle.NO_BORDER);
            c1.setPadding(6f);
            summaryTable.addCell(c1);

            PdfPCell c2 = new PdfPCell(new Phrase(loanId, valueFont));
            c2.setBorder(Rectangle.NO_BORDER);
            c2.setPadding(6f);
            summaryTable.addCell(c2);

            PdfPCell c3 = new PdfPCell(new Phrase("Interest Rate", labelFont));
            c3.setBorder(Rectangle.NO_BORDER);
            c3.setPadding(6f);
            summaryTable.addCell(c3);

            PdfPCell c4 = new PdfPCell(new Phrase(rateOfInterest, valueFont));
            c4.setBorder(Rectangle.NO_BORDER);
            c4.setPadding(6f);
            summaryTable.addCell(c4);

            // Row 2 (placeholders for now)
            PdfPCell c5 = new PdfPCell(new Phrase("Customer", labelFont));
            c5.setBorder(Rectangle.NO_BORDER);
            c5.setPadding(6f);
            summaryTable.addCell(c5);

            PdfPCell c6 = new PdfPCell(new Phrase(customerPlaceholder, valueFont));
            c6.setBorder(Rectangle.NO_BORDER);
            c6.setPadding(6f);
            summaryTable.addCell(c6);

            PdfPCell c7 = new PdfPCell(new Phrase("Tenure", labelFont));
            c7.setBorder(Rectangle.NO_BORDER);
            c7.setPadding(6f);
            summaryTable.addCell(c7);

            PdfPCell c8 = new PdfPCell(new Phrase(tenurePlaceholder, valueFont));
            c8.setBorder(Rectangle.NO_BORDER);
            c8.setPadding(6f);
            summaryTable.addCell(c8);

            // Draw light border around summary
            PdfPCell wrapper = new PdfPCell(summaryTable);
            wrapper.setBorderColor(new BaseColor(220, 220, 220));
            wrapper.setPadding(6f);
            wrapper.setColspan(1);
            PdfPTable outer = new PdfPTable(1);
            outer.setWidthPercentage(100);
            outer.addCell(wrapper);
            document.add(outer);

            document.add(Chunk.NEWLINE);

            // ---------- Table: repayment schedule ----------
            PdfPTable table = new PdfPTable(new float[]{1.0f, 1.5f, 1.5f, 1.5f, 1.2f, 1.5f, 1.5f});
            table.setWidthPercentage(100);
            table.setHeaderRows(1);

            Font thFont = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, HEADER_TEXT);
            Font tdFont = new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL, BaseColor.BLACK);

            // Header cells
            PdfPCell h;

            h = new PdfPCell(new Phrase("#", thFont));
            h.setBackgroundColor(HEADER_BG);
            h.setHorizontalAlignment(Element.ALIGN_CENTER);
            h.setPadding(8);
            h.setBorderWidth(0.5f);
            table.addCell(h);

            h = new PdfPCell(new Phrase("Loan ID", thFont));
            h.setBackgroundColor(HEADER_BG);
            h.setHorizontalAlignment(Element.ALIGN_CENTER);
            h.setPadding(8);
            h.setBorderWidth(0.5f);
            table.addCell(h);

            h = new PdfPCell(new Phrase("Due Date", thFont));
            h.setBackgroundColor(HEADER_BG);
            h.setHorizontalAlignment(Element.ALIGN_CENTER);
            h.setPadding(8);
            table.addCell(h);

            h = new PdfPCell(new Phrase("Payment Date", thFont));
            h.setBackgroundColor(HEADER_BG);
            h.setHorizontalAlignment(Element.ALIGN_CENTER);
            h.setPadding(8);
            table.addCell(h);

            h = new PdfPCell(new Phrase("Amount Paid (₹)", thFont));
            h.setBackgroundColor(HEADER_BG);
            h.setHorizontalAlignment(Element.ALIGN_RIGHT);
            h.setPadding(8);
            table.addCell(h);

            h = new PdfPCell(new Phrase("Interest Rate", thFont));
            h.setBackgroundColor(HEADER_BG);
            h.setHorizontalAlignment(Element.ALIGN_RIGHT);
            h.setPadding(8);
            table.addCell(h);

            h = new PdfPCell(new Phrase("Balance Remaining (₹)", thFont));
            h.setBackgroundColor(HEADER_BG);
            h.setHorizontalAlignment(Element.ALIGN_RIGHT);
            h.setPadding(8);
            table.addCell(h);

            // Rows
            BigDecimal totalPaid = BigDecimal.ZERO;
            BigDecimal totalOutstanding = BigDecimal.ZERO;
            int idx = 0;

            if (reportData == null || reportData.isEmpty()) {
                PdfPCell emptyRow = new PdfPCell(new Phrase("No records found", tdFont));
                emptyRow.setColspan(7);
                emptyRow.setHorizontalAlignment(Element.ALIGN_CENTER);
                emptyRow.setPadding(12);
                table.addCell(emptyRow);
            } else {
                for (RepaymentReportDTO r : reportData) {
                    idx++;

                    boolean alt = idx % 2 == 0;

                    PdfPCell cell;

                    // # (index)
                    cell = new PdfPCell(new Phrase(String.valueOf(idx), tdFont));
                    cell.setBackgroundColor(alt ? ROW_ALT : BaseColor.WHITE);
                    cell.setPadding(6);
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.addCell(cell);

                    // Loan ID
                    cell = new PdfPCell(new Phrase(r.getLoanId() != null ? String.valueOf(r.getLoanId()) : "-", tdFont));
                    cell.setBackgroundColor(alt ? ROW_ALT : BaseColor.WHITE);
                    cell.setPadding(6);
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.addCell(cell);

                    // Due Date
                    cell = new PdfPCell(new Phrase(r.getDueDate() != null ? r.getDueDate().format(df) : "-", tdFont));
                    cell.setBackgroundColor(alt ? ROW_ALT : BaseColor.WHITE);
                    cell.setPadding(6);
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.addCell(cell);

                    // Payment Date
                    cell = new PdfPCell(new Phrase(r.getPaymentDate() != null ? r.getPaymentDate().format(df) : "-", tdFont));
                    cell.setBackgroundColor(alt ? ROW_ALT : BaseColor.WHITE);
                    cell.setPadding(6);
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.addCell(cell);

                    // Amount Paid (right aligned)
                    String amt = r.getAmountPaid() != null ? r.getAmountPaid().toPlainString() : "0";
                    cell = new PdfPCell(new Phrase(amt, tdFont));
                    cell.setBackgroundColor(alt ? ROW_ALT : BaseColor.WHITE);
                    cell.setPadding(6);
                    cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                    table.addCell(cell);

                    // Interest Rate (right aligned)
                    String roi = r.getRateofinterest() != null ? r.getRateofinterest().toPlainString() + "%" : "-";
                    cell = new PdfPCell(new Phrase(roi, tdFont));
                    cell.setBackgroundColor(alt ? ROW_ALT : BaseColor.WHITE);
                    cell.setPadding(6);
                    cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                    table.addCell(cell);

                    // Balance Remaining (right aligned)
                    String bal = r.getBalanceRemaining() != null ? r.getBalanceRemaining().toPlainString() : "0";
                    cell = new PdfPCell(new Phrase(bal, tdFont));
                    cell.setBackgroundColor(alt ? ROW_ALT : BaseColor.WHITE);
                    cell.setPadding(6);
                    cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                    table.addCell(cell);

                    // Totals
                    if (r.getAmountPaid() != null) totalPaid = totalPaid.add(r.getAmountPaid());
                    if (r.getOutstanding() != null) totalOutstanding = totalOutstanding.add(r.getOutstanding());
                }
            }

            document.add(table);

            // ---------- Totals summary ----------
            document.add(Chunk.NEWLINE);

            PdfPTable totals = new PdfPTable(new float[]{1, 1});
            totals.setWidthPercentage(40);
            totals.setHorizontalAlignment(Element.ALIGN_RIGHT);

            Font totalsLabel = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, NAVY);
            Font totalsValue = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, BaseColor.BLACK);

            PdfPCell labelCell = new PdfPCell(new Phrase("Total Amount Paid:", totalsLabel));
            labelCell.setBorder(Rectangle.NO_BORDER);
            labelCell.setPadding(4);
            totals.addCell(labelCell);

            PdfPCell valueCell = new PdfPCell(new Phrase(totalPaid.toPlainString(), totalsValue));
            valueCell.setBorder(Rectangle.NO_BORDER);
            valueCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            valueCell.setPadding(4);
            totals.addCell(valueCell);

            PdfPCell labelCell2 = new PdfPCell(new Phrase("Total Outstanding:", totalsLabel));
            labelCell2.setBorder(Rectangle.NO_BORDER);
            labelCell2.setPadding(4);
            totals.addCell(labelCell2);

            PdfPCell valueCell2 = new PdfPCell(new Phrase(totalOutstanding.toPlainString(), totalsValue));
            valueCell2.setBorder(Rectangle.NO_BORDER);
            valueCell2.setHorizontalAlignment(Element.ALIGN_RIGHT);
            valueCell2.setPadding(4);
            totals.addCell(valueCell2);

            document.add(totals);

            document.add(Chunk.NEWLINE);

            // Footer brand line
            Paragraph brand = new Paragraph("© " + java.time.Year.now().getValue() + " CoreBank Pvt. Ltd.  |  Confidential", new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL, BaseColor.GRAY));
            brand.setAlignment(Element.ALIGN_CENTER);
            document.add(brand);

            document.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Error generating PDF report: " + e.getMessage(), e);
        }
    }

    // Example DTO signature (for reference) - ensure your actual DTO has these getters:
    // public static class RepaymentReportDTO {
    //     Long loanId;
    //     LocalDate dueDate;
    //     LocalDate paymentDate;
    //     BigDecimal amountPaid;
    //     BigDecimal rateofinterest;
    //     BigDecimal balanceRemaining;
    //     BigDecimal outstanding;
    //     // getters...
    // }
}
